### ISSUE TITLE
Great work!  Add this GitHub repo to AMO

### ISSUE THREAD

**Issue by Gitoffthelawn** [sanspace/add-https#1]
Great work!

You may want to add this GitHub repo to AMO.  There is a place where you can add "Add-on home page", "Support site", and "Support email" so they can be displayed within AMO.

**Comment by sanspace** [comment]
Thank you for the information and your comments!

I have added the repo and issues URL to the AMO site. https://addons.mozilla.org/en-US/firefox/addon/add-https/

**Comment by Gitoffthelawn** [comment]
You're welcome.  I confirmed the changes on AMO.  Looks great!
