### ISSUE TITLE
Option to add button within #urlbar

### ISSUE THREAD

**Issue by Gitoffthelawn** [sanspace/add-https#2]
I was thinking of writing a CSS hack to move the _Add HTTPS_ toolbar button within `#urlbar`.  I was thinking of moving it immediately left of the vertical separator line that is to the left of the URL.

That way, it will always be much closer to the actual `http` or `https` text in the URL.

Of course, the button icon will have to be changed to something different, otherwise it will get confused with the browser's "HTTPS enabled" icon.

Anyways, if this idea interests you, maybe you just add it to the actual extension so everyone can enjoy it.

**Comment by sanspace** [comment]
This was my first ever add-on. I will try to move the button as suggested. I am not sure how far I will be able to go though.

Regarding the icon, it was the closest thing I could find among the stock images. I'll be glad if anyone pitches in.

**Comment by Gitoffthelawn** [comment]
For your first ever add-on, it's excellent.  Even for an experienced add-on developer, it's excellent! :-)

**Comment by Gitoffthelawn** [comment]
I found an add-on that has an option to put its toolbar button within `#urlbar`.

It's called _Scroll Up Folder_, and it's here on GitHub: https://github.com/PerfectSlayer/scrollupfolder

Within its options, there is a checkbox called "Show button in address bar".  This results in the button being placed towards the right end of the `#urlbar`, which makes sense for that add-on.  For your add-on, placing it immediately left of the vertical separator line that is to the left of the URL makes more sense.

**Comment by Gitoffthelawn** [comment]
I was reviewing the code for [_Scroll Up Folder_](https://github.com/PerfectSlayer/scrollupfolder).  Here is the code he used for putting the button within the `#urlbar`:

https://github.com/PerfectSlayer/scrollupfolder/blob/master/lib/urlbutton.js

In particular, this might be helpful:

https://github.com/PerfectSlayer/scrollupfolder/blob/master/lib/urlbutton.js#L57

**Comment by sanspace** [comment]
This should be done when we use a pageAction when we port it to web extensions.

Closing this one and we'll further track it with #5 as there's already a conversation on web extensions API.
