### ISSUE TITLE
Ping Mozilla regarding newest version

### ISSUE THREAD

**Issue by Gitoffthelawn** [sanspace/add-https#3]
I noticed that the latest version is not available on AMO.  Can you ping them to see why not?

**Comment by sanspace** [comment]
I've submitted a new version for review today. I will update once I hear from them.

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by sanspace** [comment]
Add HTTPS, 0.0.5, has been preliminarily reviewed and is now available for download in the gallery at https://addons.mozilla.org/addon/add-https/

**Comment by Gitoffthelawn** [comment]
Thank you! :+1:
