### ISSUE TITLE
Make compatible with e10s

### ISSUE THREAD

**Issue by Gitoffthelawn** [sanspace/add-https#5]
Can you make this e10s-compatible?  It might just require setting the flag.

BTW, the actual source does not appear to be here on GitHub.

**Comment by sanspace** [comment]
Sure. Please  let me check what's going on. Thank you.

**Comment by sanspace** [comment]
@Gitoffthelawn I did not understand the source part.

https://addons.mozilla.org/en-US/firefox/files/browse/459075/file/index.js#top

https://github.com/sanspace/add-https/blob/master/index.js

You meant to say mozilla and github have different versions of source?

**Comment by Gitoffthelawn** [comment]
Sorry, I wasn't clear.  Some of the files are missing, such as `install.rdf`.

Thanks for looking at e10s compatibility.

BTW, do you think you could use the WebExtensions API?

**Comment by sanspace** [comment]
Actually, I'm on it. Just getting started and fiddling with the APIs.

**Comment by sanspace** [comment]
https://github.com/sanspace/add-https/tree/webext

I am not sure if I'm using the Web Extension APIs the right way. I could use your inputs.

Thank you.

**Comment by Gitoffthelawn** [comment]
You're one step ahead of me! :)  I haven't had much chance to look at the WebExtensions API yet.

I took a look at your code, and well, the logic looks good, but I don't currently have the knowledge to evaluate the API usage.  Sorry about that.

But I'm excited you are working on the port to WebExtensions.  Once you are done, I'll send you a tiny extension I wrote in XUL for a WebExtension overhaul!

**Comment by sanspace** [comment]
I'm done though I'm very late. Commit 34b8f65060c4f3c41c6716fb265861eb2c4fce0f 

Please share your extension. I'll see what I can do. Can't promise an exact ETA though.

**Comment by Gitoffthelawn** [comment]
Sounds great.  I will!

And thank you for the new version.  It's fantastic!

**Comment by sanspace** [comment]
Please share your extension. As I myself might take a long time to get it done, you got to be faster! 😃

**Comment by Gitoffthelawn** [comment]
:) Will do!  I just moved it up on my list! :)
